config/routes.rb
Rails.application.routes.draw do

  get 'likes/create'
  get 'likes/destroy'
  devise_for :users
  get 'lectures', to: 'lectures#index'
  get 'toppages', to: 'toppages#index'

  resources :likes, only: [:create, :destroy]
  root to: 'toppages#index'

  post 'uploader/upload'

  resources :problems, only: [:create, :destroy]
  
  resources :editors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/editor.rb
class Editor < ApplicationRecord
  belongs_to :user
  has_many :problems, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  validates :title, presence: true
  validates :description, presence: true
  accepts_nested_attributes_for :problems, allow_destroy: true
  
  def like?(user)
    like_users.include?(user)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :editor
  counter_culture :editor
end

app/models/problem.rb
class Problem < ApplicationRecord
  belongs_to :editor
  
  validates :question, presence: true
  validates :answer, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
  has_many :editors
  has_many :likes, dependent: :destroy
  has_many :like_editors, through: :likes, source: :editor
  
  include Gravtastic
    gravtastic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name]) # 新規登録時(sign_up時)にnameというキーのパラメーターを追加で許可する
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image, :profile])
  end
  
  def after_sign_in_path_for(resource)
    lectures_path # ログイン後に遷移するpathを設定
  end

  private

end

app/controllers/editors_controller.rb
class EditorsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_editor, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:destroy]

  # GET /editors
  # GET /editors.json
  def index
    if user_signed_in?
      @editor = current_user.editors.build  
      @editors = current_user.editors.order('created_at DESC').page(params[:page])
    end
  end

  # GET /editors/1
  # GET /editors/1.json
  def show
    @editor = Editor.find(params[:id])
    @problems = @editor.problems.order('created_at DESC')
  end

  # GET /editors/new
  def new
    @editor = Editor.new
    @editor.problems.build
  end

  # GET /editors/1/edit
  def edit
  end

  # POST /editors
  # POST /editors.json
  def create
    @editor = current_user.editors.build(editor_params)

    respond_to do |format|
      if @editor.save
        format.html { redirect_to @editor, notice: 'Editor was successfully created.' }
        format.json { render :show, status: :created, location: @editor }
      else
        format.html { render :new }
        format.json { render json: @editor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /editors/1
  # PATCH/PUT /editors/1.json
  def update
    respond_to do |format|
      if @editor.update(editor_params)
        format.html { redirect_to @editor, notice: 'Editor was successfully updated.' }
        format.json { render :show, status: :ok, location: @editor }
      else
        format.html { render :edit }
        format.json { render json: @editor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /editors/1
  # DELETE /editors/1.json
  def destroy
    @editor.destroy
    respond_to do |format|
      format.html { redirect_to editors_url, notice: 'Editor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_editor
      @editor = Editor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def editor_params
      params.require(:editor).permit(:title, :description,
                                     problems_attributes: [:question,:answer, :_destroy])
    end
    
    def correct_user
      @editor = current_user.editors.find_by(id: params[:id])
      unless @editor
        redirect_to root_url
      end
    end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  def index
    @editors_all = Editor.all
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @editor = Editor.find(params[:editor_id])
    @like = current_user.likes.find_by(editor: @editor)
    toggle
  end

  private

    def toggle
      if @like
        return head :unprocessable_entity unless @like.destroy
      else
        @like = current_user.likes.build(editor: @editor)
        return head :unprocessable_entity unless @like.save
      end
      head :ok
    end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  def new
    @problem = Problem.new
  end  
  
  def create
    @problem = Problem.new(problem_params)
  end

  def destroy
  end
  
  # ~
  private
  def problem_params
    params.require(:problem).permit(
      Problem::ALLOWED_PARAMS,
      editors_attributes: Editor::NESTED_ALLOWED_PARAMS
    )
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  layout 'top_layout'
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/editors_helper.rb
module EditorsHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # 与えられたユーザーのGravatar (http://gravatar.com/) を返す。
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Microposts</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to 'Users', users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'My profile', user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Logout', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Signup', signup_path %></li>
            <li><%= link_to 'Login', login_path %></li>
            <li><%= link_to 'Logout', logout_path, method: :delete %></li>            
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang = 'en'>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tands" %></title>
    <%= csrf_meta_tags %>


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
 
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 

    <!-- jQuery -->

    <!-- Bootstrap JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="https://rawgit.com/RickStrahl/jquery-resizable/master/dist/jquery-resizable.min.js"></script>
    

  

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <!-- %= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <!-- %= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <!-- %= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <!--%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <!-- %= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>


    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Tands</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <% if user_signed_in? %>
            <ul class="nav navbar-nav">
              <li>
                <%= link_to "Student", lectures_path  %>
              </li>
              <li><%= link_to "Teacher", editors_path  %></li>
              <li><%= link_to "Profile", edit_user_registration_path  %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
    <div class="container col-lg-9">
      <%= render 'layouts/flash_messages' %>

    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-10">
          <%= yield %>
        </div>
      <div>
      
    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/top_layout.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Title</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag "top/top", :media => "all" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div id="wrapper">
      <%= yield %>
    </div>
  </body>
</html>